- name: Stopping the server service
  service:
    name: "{{ service_name }}"
    state: stopped

- name: Removing the original folder
  file:
    path: "{{ server_root }}"
    state: absent

- name: Copying the new buid
  copy:
    remote_src: yes
    src: "{{ server_deploy_dir }}/"
    dest: "{{ server_root }}"

- name: Copying the configuration
  shell:
    chdir: "{{ config_script_dir }}"
    cmd: "{{ config_script_dir }}/{{ config_script_name }}"

- name: Starting the server service
  service:
    name: "{{ service_name }}"
    state: started
  