# Playbook to install the infrastructure needed to run the Server and the Webapp
- name: Install Nginx
  hosts: main_server

  roles:
    - ansible-role-nginx

- name: Install .NET Core
  hosts: main_server

  roles:
    - ansible-role-dotnet-core
  vars:
    - dotnet_package: "dotnet-sdk-3.1"  