name: build-and-publish
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build using Dotnet 3.1.x
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '3.1.x'
            - name: Build app
              run: dotnet publish --configuration Release
            - name: Publish binaries
              uses: actions/upload-artifact@v2
              with:
                name: binaries
                path: bin/Release/